# Generated by Django 4.2.30 on 2026-09-26 17:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('productos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MovimientoInventario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('entrada', 'Entrada (reabastecimiento)'), ('salida', 'Salida (venta)'), ('ajuste', 'Ajuste manual')], max_length=10)),
                ('cantidad', models.IntegerField(help_text='Positivo para entradas, negativo para salidas.')),
                ('existencias_resultantes', models.PositiveIntegerField()),
                ('motivo', models.CharField(blank=True, max_length=200)),
                ('referencia_pedido', models.CharField(blank=True, help_text='ID del pedido que originó el movimiento, si aplica.', max_length=50)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movimientos_inventario', to='productos.producto')),
            ],
            options={
                'verbose_name': 'Movimiento de inventario',
                'verbose_name_plural': 'Movimientos de inventario',
                'ordering': ['-creado'],
            },
        ),
    ]
